Fix old sessions
dancier/show-dancer pull request #106
Opened 2022-07-27 09:44 UTC by jans510

2022-07-27 21:08 UTC, halbekanne requested changes

2022-07-27 21:08 UTC, halbekanne commented on src/app/features/home/pages/contact/contact.component.html
> +        <ng-container *ngIf="!authData.isHuman">
Das gleiche wie in der anderen Datei, können wir so nicht machen sonst verschwindet das Captcha sobald der Nutzer das Captcha löst und die darunter liegenden Elemente verschieben sich nach oben.

2022-07-27 21:08 UTC, halbekanne commented on src/app/features/home/pages/contact/contact.component.ts
> +            default:
Das gleiche wie im anderen File.

2022-07-28 05:15 UTC, jans510 commented on src/app/features/home/components/beta-signup-form/beta-signup-form.component.ts
> +              this.errorMessage = 'Vielen Dank, Du hast Dich bereits zuvor für die Beta registriert.'
ich finde das mir dem ngif ein wenig unübersichtlich, vor allem wenn wir mehrere verschiedene Fehlermeldungen haben und jedes mal einen neuen mat-error erstellen würden.

2022-07-28 05:41 UTC, jans510 commented on src/app/features/home/components/beta-signup-form/beta-signup-form.component.html
> +      <ng-container *ngIf="!authData.isHuman">
ah ok, dann änder ich das mal...

2022-07-28 05:44 UTC, jans510 commented on src/app/features/home/components/beta-signup-form/beta-signup-form.component.ts
> +            default:
hmm, der server error ist ja sozusagen der default vom server wenn nichts spezielleres gesendet wird, und wir mappen es im Frontend auf eine generische Fehlermeldung. Von daher finde ich es eigentlich in Ordnung das im frontend unter default laufen zu lassen.

2022-07-28 06:03 UTC, jans510 commented on src/app/features/home/components/beta-signup-form/beta-signup-form.component.html
> +      <ng-container *ngIf="!authData.isHuman">
ich würde aber den Ansatz mit authdata.isHuman beibehalten, dafür wurde das ja entwickelt und wir sollten nicht in verschiedenen Komponenten andere Ansätze haben, den session status zu bekommen, sonst führt das zu den Problemen wie mit dem PR hier, das jemand das wieder ändert. Da es hier ein Spezialfall ist würde ich eine zweite Variable einführen, dadurch wird der Unterschied auch besser deutlich zum abgeänderten Standardverhalten.

2022-07-29 15:25 UTC, halbekanne approved these changes

2022-07-29 15:25 UTC, merged