Chat overview
dancier/show-dancer pull request #156
Opened 2022-12-14 11:56 UTC by jans510

2022-12-14 11:57 UTC, jans510 commented
I will continue on this PR until functionality is implemented to show chats and messages undesigned

2022-12-15 11:04 UTC, jans510 commented
@halbekanne first PR is open for review and to discuss the approach

2022-12-20 14:01 UTC, halbekanne requested changes

2022-12-20 14:02 UTC, halbekanne commented
There are failing tests.

2022-12-20 14:52 UTC, jans510 commented on src/app/app.component.ts
> +    private chatService: ChatService // needs to be initialized from the start
this would be needed if we want to show the user that there are unread messages even if the user had not yet open the chat.
Therefore we need to have a polling for new entries from the beginning when the user is logged in

2022-12-20 15:03 UTC, jans510 commented on src/app/features/chat/common/pipes/partner.pipe.ts
> +  getPartner(chat: Chat, ownId: DancerId, dancers: DancerMap): Dancer {
I will create a chat partner component that will do the whole transformation ...

2022-12-21 22:04 UTC, halbekanne commented on src/app/app.component.ts
> +    private chatService: ChatService // needs to be initialized from the start
I understand. I think you could do that by importing it in components that use that information, e.g. the navigation bar component.

2022-12-22 15:00 UTC, jans510 commented on src/app/app.component.ts
> +    private chatService: ChatService // needs to be initialized from the start
I will change it with the next PR, then this PR could be merged

2022-12-27 19:52 UTC, halbekanne approved these changes

2022-12-28 07:33 UTC, merged