first version of image uploader
dancier/show-dancer pull request #53
Opened 2022-06-16 19:47 UTC by jans510

2022-06-16 20:01 UTC, gorzala approved these changes

2022-06-18 09:44 UTC, gorzala commented on src/app/app.component.ts
> +const STYLES = (theme: ThemeVariables, ref: ThemeRef) => {
please fix ;-)

2022-06-18 14:32 UTC, halbekanne requested changes
Paar generelle Punkte in der Review über die wir nochmal sprechen sollten, auch ein paar Sachen die man auch in der nächsten Version noch angehen könnte, kannst mich auch gerne dazu anrufen wenn es dir praktischer erscheint statt schreiben.

2022-06-18 14:32 UTC, halbekanne commented on src/app/app.component.ts
> +const STYLES = (theme: ThemeVariables, ref: ThemeRef) => {
dieses alyle UI erlaubt nicht einfach die Styles in der scss reinzusetzen? Das braucht einen eigenen StyleRenderer mit tagged template strings? Das kommt mir wo ich mir das so anschaue unnötig vor. Da wir nur diesen ImageUploader brauchen sollten wir das nochmal nachschauen ob das so ist.

2022-06-18 14:32 UTC, halbekanne commented on src/app/app.module.ts
> +  }, StyleRenderer, LyTheme2, { provide: LY_THEME_NAME, useValue: 'minima-light' }, {
und hier noch irgendwelche Themes speziell dafür definieren? Kommt mir auch etwas viel vor für die eine Komponente, wir pflegen ja schon unser Material UI Theme, brauchts da die Pflege einer weiteren? Für einen Prototypen ganz gute Lösung, aber wir sollten uns später den anderen Image-Cropper nochmal anschauen. Wenn das mehr in Richtung einer Library geht als der von Alyle, der eher Teil einer kompletten Komponenten-Lib ist die wir nicht nutzen, würde ich langfristig zu der Library tendieren und unsere eigene Komponente drum rum basteln.

2022-06-18 14:32 UTC, halbekanne commented on src/app/data/services/image-upload.service.ts
> +  uploadImage(croppedImage: string): Observable<ImageUploadResponse> {
ist jetzt die Grunsatzfrage, wollen wir Methoden und Variablen die Observables sind per Konvention mit Dollar ($) enden lassen oder nicht?

2022-06-18 14:32 UTC, halbekanne commented on src/app/features/home/home.module.ts
> +    LyIconModule,
s.o.

2022-06-18 14:32 UTC, halbekanne commented on src/app/features/home/home.module.ts
> +import { LyIconModule } from '@alyle/ui/icon';
Slider, Button, Icon, brauchen wir die? Dachte mir der Image Cropper reicht uns und der Rest sind Material Komponenten.

2022-06-18 14:32 UTC, halbekanne commented on src/app/features/home/pages/image-upload/image-upload.component.ts
> +});
gleiche Frage wie oben, muss man das wirklich so machen? Ich kenne das aus Angular so nicht, normal sind die Styles in der scss-Datei der Komponente.

2022-06-18 14:32 UTC, halbekanne commented on src/app/features/home/pages/image-upload/image-upload.component.ts
> +        yOrigin: 236.26357452128866,
Wie kommen die Zahlen zustande?

2022-06-18 14:58 UTC, jans510 commented on src/app/features/home/home.module.ts
> +import { LyIconModule } from '@alyle/ui/icon';
stimmt, die hatte ich umgestellt, ich entferne die hier...

2022-06-18 14:59 UTC, jans510 commented on src/app/features/home/pages/image-upload/image-upload.component.ts
> +});
das wollte ich noch ändern, der PR war erst mal nur zum testen und noch nicht final

2022-06-18 15:29 UTC, jans510 commented on src/app/features/home/pages/image-upload/image-upload.component.ts
> +        yOrigin: 236.26357452128866,
das war die Config für das default Bild (praktisch ein default crop). Da wir aber kein default image haben, hab ich die Config entfernt

2022-06-18 19:32 UTC, manuela2013 commented on src/app/features/home/pages/image-upload/image-upload.component.ts
> +        yOrigin: 236.26357452128866,
Good to know that, I'll create some design these days and then we know which default size we expected and then we can change the config.

2022-06-20 17:12 UTC, closed without merging