Event queue
dancier/show-dancer pull request #64
Opened 2022-07-02 17:15 UTC by jans510

2022-07-07 18:53 UTC, halbekanne requested changes

2022-07-07 18:53 UTC, halbekanne commented on src/app/data/types/eventlog.types.ts
> +export type EventLogEvent = {
2 Mal Event im Namen, wie wärs denn mit "Event" oder "EventLogPayload" oder so?

2022-07-07 18:53 UTC, halbekanne commented on src/app/data/services/event-log-http.service.ts
> +  postEvent(event: EventLogEvent): Observable<PostEventResponse> {
Dollar am Ende von Namen von Methoden die Observables zurück liefern?

2022-07-07 18:53 UTC, halbekanne commented on src/app/data/services/event-log.service.ts
> +  getEventObservable(): Observable<PostEventResponse> {
Ich versteh das noch nicht, wieso brauchen wir die Methode, wieso will jemand die Events observen? Und wieso halten wir eine Subscription in der App Component? Reicht es nicht die Events mit createAndPublishEvents direkt auch zu verschicken?

2022-07-07 18:53 UTC, halbekanne commented on src/app/app.component.ts
> +    this.eventObservableSubscription = this.eventLogService
Wieso subscriben wir, wir machen in der Komponente nichts damit oder?

2022-07-07 19:32 UTC, jans510 commented on src/app/data/types/eventlog.types.ts
> +export type EventLogEvent = {
ja, habs jetzt einfach event genannt

2022-07-08 16:51 UTC, gorzala approved these changes

2022-07-08 17:54 UTC, merged